format = "peipkg"

[package]
version       = "{{version}}-1"
architecture  = "x86_64"
license       = "MIT AND Apache-2.0 AND BSD-3-Clause AND ISC AND Unicode-3.0 AND Unlicense"
license_class = "free"
homepage      = "https://github.com/peios/pnp"
